# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

GROUP = "jenkins-master"
HOST = "localhost"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.define HOST

  config.vm.provision :ansible do |ansible|
    ansible.groups = {
      GROUP => [HOST]
    }
    ansible.playbook = "../../strikead/shrike/playbooks/jenkins-master.yml"
    ansible.extra_vars = { skip_apt_update: true }
  end
end
