# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX      = "ubuntu/trusty64"
URL      = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
HOST     = "localhost"
GROUP    = "jenkins-master"

Vagrant.configure(2) do |config|
  config.vm.box = BOX
  config.vm.box_url = URL
  config.vm.host_name = "jenkins-master"
  config.vm.define HOST

  config.vm.network "private_network", ip: "192.168.100.200"
  config.vm.network "forwarded_port", guest: 8080, host: 8280
  #config.vm.network "forwarded_port", guest: 8081, host: 9091
  #config.vm.network "forwarded_port", guest: 9000, host: 9009


  ENV['LC_ALL']="en_US.UTF-8"

  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
  end

  config.vm.provision :ansible do |ansible|
    ansible.groups = {
      GROUP => [HOST]
    }
    install = true
    ansible.playbook = "../playbooks/git.yml"
    ansible.extra_vars = { skip_apt_update: true }
  end
end
